//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog3Final
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Departamento
    {
        [Key]
        public int id { get; set; }

        public string Codigo { get; set; }

        public string Nombre { get; set; }

        public int Encargado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
