//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog3Final
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vacacione
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="Se necesita el codigo del empleado")]
        public int IdEmpleado { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Se necesita la fecha de inicio")]
        public DateTime Desde { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Se necesita la fecha de fin")]
        public DateTime Hasta { get; set; }
        
        [Range(2019, 2100, ErrorMessage ="Ingrese un año")]
        public int Año { get; set; }

        [Required]
        [MaxLength(100, ErrorMessage = "Solo son permitidos 100 Caracteres")]
        public string Comentarios { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
